# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ "dev" ]

jobs:
          
  build:

    strategy:
      matrix:
        type: [Android, Windows, Linux, macOS]
        include:
          - type: Android
            os: macos-latest
          - type: Windows
            isDesktop: true
            os: windows-latest
          - type: Linux
            isDesktop: true
            os: ubuntu-latest
          - type: macOS
            isDesktop: true
            os: macos-latest
    runs-on: ${{ matrix.os }}
      
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        
    - name: Build Android
      if: ${{ matrix.type == 'Android' }}
      run: |
        echo "$ANDROID_KEYSTORE" | base64 --decode > ${{ github.workspace }}/android_sign_key.jks
        echo "$ANDROID_SIGNING_PASSWORD" >  ${{ github.workspace }}/ANDROID_SIGNING_PASSWORD.txt
        echo "$ANDROID_SIGNING_KEY_ALIAS" >  ${{ github.workspace }}/ANDROID_SIGNING_KEY_ALIAS.txt
        echo "$ANDROID_SIGNING_KEY_PASSWORD" >  ${{ github.workspace }}/ANDROID_SIGNING_KEY_PASSWORD.txt
        # ./gradlew :gallery:assembleRelease
      env:
        ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        ANDROID_SIGNING_FILE: ${{ github.workspace }}/android_sign_key.jks
        ANDROID_SIGNING_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
    # - name: Build Desktop
    #   if: ${{ matrix.isDesktop }}
    #   run: |
    #     ./gradlew :gallery:packageReleaseDistributionForCurrentOS
    - name: pack artifacts
      uses: actions/upload-artifact@v4
      with:
          name: distributions-${{ matrix.type }}
          path: |
            ${{ github.workspace }}/gallery/build/compose/**/*.deb
            ${{ github.workspace }}/gallery/build/compose/**/*.rpm
            ${{ github.workspace }}/gallery/build/compose/**/*.msi
            ${{ github.workspace }}/gallery/build/compose/**/*.exe
            ${{ github.workspace }}/gallery/build/compose/**/*.dmg
            ${{ github.workspace }}/gallery/build/compose/**/*.pkg
            ${{ github.workspace }}/gallery/**/*.apk
            # ${{ github.workspace }}/android_sign_key.jks
            # ${{ github.workspace }}/ANDROID_SIGNING_PASSWORD.txt
            # ${{ github.workspace }}/ANDROID_SIGNING_KEY_ALIAS.txt
            # ${{ github.workspace }}/ANDROID_SIGNING_KEY_PASSWORD.txt
      
